# Generated by Django 4.0.2 on 2022-12-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdf')),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
